--- 
- name: Deploy Maven Artifact 
  hosts: local 
  become: yes 
  tasks: 
  - name: Copy the artifact to deployment directory 
    copy: 
     src: "/var/lib/jenkins/workspace/MyMavenApp/target/MyMavenApp-1.0-SNAPSHOT.jar" 
     dest: "/opt/deployment/MyMavenApp.jar" 
